<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Autofac" Version="9.1.0" />
    <PackageVersion Include="Autofac.Extensions.DependencyInjection" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Maui.Controls" Version="10.0.60" />
    <PackageVersion Include="Microsoft.Maui.Controls.Compatibility" Version="10.0.60" />
    <PackageVersion Include="Microsoft.Maui.Essentials" Version="10.0.60" />
    <PackageVersion Include="Microsoft.Maui.Platforms.Linux.Gtk4" Version="0.1.0-preview.12.26358.3" />
    <PackageVersion Include="Microsoft.Maui.Platforms.Linux.Gtk4.Essentials" Version="0.1.0-preview.12.26358.3" />
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageVersion Include="sqlite-net-pcl" Version="1.9.172" />
    <PackageVersion Include="SQLitePCLRaw.lib.e_sqlite3" Version="3.53.3" />
    <PackageVersion Include="SQLiteNetExtensions" Version="2.1.0" />
    <PackageVersion Include="SQLiteNetExtensions.Async" Version="2.1.0" />
    <PackageVersion Include="SQLitePCLRaw.bundle_green" Version="2.1.11" />
    <PackageVersion Include="ZXing.Net.Maui.Controls" Version="0.7.4" />
  </ItemGroup>
  <ItemGroup>
    <!--unit / component tests-->
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="FluentAssertions" Version="7.2.2" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.3.0" />
    <PackageVersion Include="Moq" Version="4.20.72" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>
</Project>
