<Project>
  <PropertyGroup>
    <SingleProject>false</SingleProject>
    <UseMaui>true</UseMaui>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <GenerateAssemblyTitleAttribute>false</GenerateAssemblyTitleAttribute>
    <GenerateAssemblyVersionAttribute>false</GenerateAssemblyVersionAttribute>
    <Nullable>enable</Nullable>
    <NeutralLanguage>en-US</NeutralLanguage>
    <AssemblyName>$(MSBuildProjectName)</AssemblyName>
  </PropertyGroup>
  <PropertyGroup Condition="'$(RootNamespace)' == ''">
    <RootNamespace>$(MSBuildProjectName)</RootNamespace>
  </PropertyGroup>
  <PropertyGroup Condition="$(MSBuildProjectName.EndsWith('.Tests'))">
    <!-- Define properties specific to test projects -->
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <!--App information-->
  <PropertyGroup>
    <ApplicationDisplayVersion>3.5</ApplicationDisplayVersion>
    <ApplicationVersion>51</ApplicationVersion>
  </PropertyGroup>
</Project>
