<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>BrickController2.Linux</RootNamespace>
    <AssemblyName>BrickController2.Linux</AssemblyName>
    <ApplicationId>de.raphaelvolz.brickcontroller</ApplicationId>
    <ApplicationTitle>BrickController</ApplicationTitle>
    <RuntimeIdentifiers>linux-x64;linux-arm64</RuntimeIdentifiers>
    <Description>Experimental Ubuntu/Linux desktop build of BrickController.</Description>
    <Authors>Istvan Murvai</Authors>
    <PackageProjectUrl>https://github.com/volzinnovation/brickcontroller2/</PackageProjectUrl>
    <DebSection>utils</DebSection>
    <DebCategories>Utility;Game;</DebCategories>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" />
    <PackageReference Include="Autofac.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Maui.Controls" />
    <PackageReference Include="Microsoft.Maui.Controls.Compatibility" />
    <PackageReference Include="Microsoft.Maui.Essentials" />
    <PackageReference Include="Microsoft.Maui.Platforms.Linux.Gtk4" />
    <PackageReference Include="Microsoft.Maui.Platforms.Linux.Gtk4.Essentials" />
    <ProjectReference Include="..\BrickController2\BrickController2.csproj" />
  </ItemGroup>

</Project>
