<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>BrickController2</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="UI\Images\*.png" />
  </ItemGroup>

  <ItemGroup>
    <!-- Custom Fonts -->
    <MauiFont Include="Resources\Fonts\*" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" />
    <PackageReference Include="Microsoft.Maui.Controls" />
    <PackageReference Include="Microsoft.Maui.Controls.Compatibility" />
    <PackageReference Include="Microsoft.Maui.Essentials" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="sqlite-net-pcl" />
    <PackageReference Include="SQLiteNetExtensions" />
    <PackageReference Include="SQLiteNetExtensions.Async" />
    <PackageReference Include="ZXing.Net.Maui.Controls" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="BrickController2.Tests" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\TranslationResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>TranslationResources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\TranslationResources.de.resx">
      <DependentUpon>TranslationResources.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\TranslationResources.hu.resx">
      <DependentUpon>TranslationResources.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\TranslationResources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>TranslationResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
</Project>
