<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
    <TargetFrameworks>net10.0-ios</TargetFrameworks>
    <RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
		<SupportedOSPlatformVersion>12.2</SupportedOSPlatformVersion>
    <OutputType>Exe</OutputType>
		<ApplicationId>de.raphaelvolz.brickcontroller</ApplicationId>
		<RootNamespace>BrickController2.iOS</RootNamespace>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
	  <BundleResource Remove="Resources\splash.svg" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="Resources\splash.svg" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Autofac" />
		<PackageReference Include="Autofac.Extensions.DependencyInjection" />
		<PackageReference Include="Microsoft.Maui.Controls" />
		<PackageReference Include="Microsoft.Maui.Controls.Compatibility" />
		<PackageReference Include="Microsoft.Maui.Essentials" />
		<ProjectReference Include="..\BrickController2\BrickController2.csproj" />
	</ItemGroup>

  <ItemGroup>
    <MauiAsset Include="..\..\LICENSE.txt" Link="OpenSource\LICENSE.txt" />
    <MauiAsset Include="..\..\THIRD_PARTY_NOTICES.txt" Link="OpenSource\THIRD_PARTY_NOTICES.txt" />
    <MauiAsset Include="..\..\Help\**\*.*" Link="Help\%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>

	<ItemGroup>
	  <Folder Include="Properties\" />
	</ItemGroup>

	<ItemGroup>
	  <MauiSplashScreen Include="Resources\splash.svg">
	    <Color>#990000</Color>
	    <BaseSize>128,128</BaseSize>
	  </MauiSplashScreen>
	</ItemGroup>

</Project>
