name: Build BrickController Android 

on:
  push:
    branches:
      - default
      - 'releases/**'
    paths:
      - '.github/**/*android.yml'
      - 'BrickController2/*.props'
      - 'BrickController2/*.sln'
      - 'BrickController2/BrickController2/**'
      - 'BrickController2/BrickController2.Android/**'
  pull_request:
    branches:    
      - default
      - 'releases/**'
    paths:
      - '.github/**/*android.yml'
      - 'BrickController2/*.props'
      - 'BrickController2/*.sln'
      - 'BrickController2/BrickController2/**'
      - 'BrickController2/BrickController2.Android/**'
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-android:
    runs-on: windows-2025
    name: BrickController Android Build
    env:
      APP_DISPLAY_VERSION: ""

    steps:

    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Install .NET MAUI Workload
      run: dotnet workload install maui-android

    - name: Find Current Release Info
      if: github.event_name == 'release' && github.event.action == 'published'
      id: get_release
      uses: octokit/request-action@v2.x
      with:
        route: GET /repos/${{ github.repository }}/releases/tags/${{ github.event.release.tag_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set APP_DISPLAY_VERSION for release
      if: github.event_name == 'release' && github.event.action == 'published'
      shell: bash 
      run: echo "APP_DISPLAY_VERSION=$(echo '${{ fromJson(steps.get_release.outputs.data).tag_name }}')" >> $GITHUB_ENV
            
    - name: Restore Dependencies
      run: dotnet restore BrickController2/BrickController2.Android/BrickController2.Android.csproj
    - name: Setup Android signing
      if: github.event_name == 'release' && github.event.action == 'published'
      shell: bash   
      run: (echo "${{secrets.KEYSTORE}}" | base64 --decode) > BrickController2/BrickController2.Android/keystore.jks
    - name: Build MAUI Android
      run: dotnet publish BrickController2/BrickController2.Android/BrickController2.Android.csproj `
        -c Release `
        -f net10.0-android `
        --no-restore `
        -p:ApplicationDisplayVersion="${{ env.APP_DISPLAY_VERSION }}" `
        -p:AndroidKeyStore=${{ github.event_name == 'release' && github.event.action == 'published' }} `
        -p:AndroidSigningKeyPass=${{secrets.KEYSTORE_PASSWORD}} `
        -p:AndroidSigningStorePass=${{secrets.KEYSTORE_PASSWORD}}

    - name: Upload Android Artifact
      uses: actions/upload-artifact@v4
      with:
        name: brickcontroller-android-ci-build
        path: BrickController2/BrickController2.Android/bin/Release/net10.0-android/*.apk

    - name: Upload Artifact to Release
      if: github.event_name == 'release' && github.event.action == 'published'
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ fromJson(steps.get_release.outputs.data).upload_url }}
        asset_path: BrickController2/BrickController2.Android/bin/Release/net10.0-android/com.scn.BrickController2-Signed.apk
        asset_name: BrickController2_${{env.APP_DISPLAY_VERSION}}.apk
        asset_content_type: application/vnd.android.package-archive
      env:
        GITHUB_TOKEN: ${{ secrets.CI_RELEASE_ASSETS_PAT }}
