name: Build BrickController Android 

on:
  push:
    branches:
      - default
      - 'releases/**'
    paths:
      - '.github/**/*android.yml'
      - 'BrickController2/*.props'
      - 'BrickController2/*.sln'
      - 'BrickController2/BrickController2/**'
      - 'BrickController2/BrickController2.Android/**'
  pull_request:
    branches:    
      - default
      - 'releases/**'
    paths:
      - '.github/**/*android.yml'
      - 'BrickController2/*.props'
      - 'BrickController2/*.sln'
      - 'BrickController2/BrickController2/**'
      - 'BrickController2/BrickController2.Android/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-android:
    runs-on: windows-2025
    name: BrickController Android Build
    steps:

    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Install .NET MAUI Workload
      run: dotnet workload install maui-android

    - name: Restore Dependencies
      run: dotnet restore BrickController2/BrickController2.Android/BrickController2.Android.csproj
    - name: Build MAUI Android
      run: dotnet publish BrickController2/BrickController2.Android/BrickController2.Android.csproj `
        -c Release `
        -f net10.0-android `
        --no-restore `
        -p:AndroidKeyStore=false

    - name: Upload Android Artifact
      uses: actions/upload-artifact@v4
      with:
        name: brickcontroller-android-ci-build
        path: BrickController2/BrickController2.Android/bin/Release/net10.0-android/*.apk
